name: Chaining Jobs
on:
  push:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}"
  job_2:
    runs-on: macos-latest
    needs: job_1
    steps:
      - run: "echo Job: ${{ github.job }}"
