# a full-line comment in YAML
name: My First Workflow # An in-line comment
on:
 push:
   branches: [main, master, pull_request, 'release/**']
   paths: ['docs/**']
 workflow_dispatch:
 watch:
   types: [started]
 schedule:
   # Runs at every 15th minute
   - cron: '*/15 * * * *'
   # Runs every hour from 9am to 5pm
   - cron: '0 9-17 * * *'
   # Runs every Friday at midnight
   - cron: '0 0 * * FRI'
   # Runs every quarter (00:00 on day 1 every 3rd month)
   - cron: '0 0 1 */3 *'

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      - name: Run echo commands
        run: |
            echo "Prince Anire"
            echo "Jacob Smith"
            echo "Jackson"
          
          
