name: Passing Information through outputs
on: [push, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.name }}
    steps:
      - id: step1
        run: echo "name=jacob" >> "$GITHUB_OUTPUT"
  dependent_job:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: echo the information passed from job1
        run: echo "${{ needs.job1.outputs.output1 }}" is the name
      - name: Write Summary from Action
        uses: actions/github-script@v8
        with:
          script: |
               await core.summary
               .addHeading('Test Results')
               .addTable([
               [{data: 'File', header: true}, {data: 'Result', header: true}],
               ['foo.js', 'Pass ✅'],
               ['bar.js', 'Fail ❌'],
               ['test.js', 'Pass ✅']
               ])
               .addLink('View staging deployment!', 'https://github.com')
               .write()
